# Generated by Django 4.2.13 on 2024-06-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_rename_author_id_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
